# This file is automatically generated by pyo3_stub_gen

import datetime
import enum
import typing

from nautilus_trader import model

__all__ = [
    "BitgetAccountMode",
    "BitgetDataClientConfig",
    "BitgetDataClientFactory",
    "BitgetEnvironment",
    "BitgetExecClientConfig",
    "BitgetExecutionClientFactory",
    "BitgetHttpClient",
    "BitgetInstrumentProviderConfig",
    "BitgetProductType",
    "BitgetRawHttpClient",
    "BitgetWebSocketClient",
    "bitget_bar_spec_to_interval",
    "bitget_extract_raw_symbol",
    "bitget_product_type_from_symbol",
    "get_bitget_http_base_url",
    "get_bitget_ws_url_private",
    "get_bitget_ws_url_public",
]

@typing.final
class BitgetDataClientConfig:
    def __init__(
        self,
        product_type: BitgetProductType | None = None,
        environment: BitgetEnvironment | None = None,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        base_url_http: str | None = None,
        base_url_ws_public: str | None = None,
        base_url_ws_private: str | None = None,
        proxy_url: str | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
        heartbeat_interval_secs: int | None = None,
        update_instruments_interval_mins: int | None = None,
        instrument_poll_interval_secs: int | None = None,
        account_mode: BitgetAccountMode | None = None,
    ) -> None: ...

@typing.final
class BitgetDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class BitgetExecClientConfig:
    def __init__(
        self,
        product_type: BitgetProductType | None = None,
        environment: BitgetEnvironment | None = None,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        base_url_http: str | None = None,
        base_url_ws_private: str | None = None,
        proxy_url: str | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
        heartbeat_interval_secs: int | None = None,
        account_id: model.AccountId | None = None,
        ignore_uncached_instrument_executions: bool | None = None,
        reconnect_reconciliation_lookback_mins: int | None = 60,
        account_mode: BitgetAccountMode | None = None,
    ) -> None: ...

@typing.final
class BitgetExecutionClientFactory:
    def __init__(self, trader_id: model.TraderId, account_id: model.AccountId) -> None: ...
    def name(self) -> str: ...

@typing.final
class BitgetHttpClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        environment: BitgetEnvironment = ...,
        base_url: str | None = None,
        timeout_secs: int = 60,
        proxy_url: str | None = None,
        account_mode: BitgetAccountMode = ...,
    ) -> None: ...
    def cancel_all_requests(self) -> None: ...
    def is_initialized(self) -> bool: ...
    def get_cached_symbols(self) -> list[str]: ...
    def cache_instrument(self, instrument: typing.Any) -> None: ...
    def cache_instruments(self, instruments: typing.Sequence[typing.Any]) -> None: ...
    def request_instruments(
        self, product_type: BitgetProductType, ts_init_ns: int | None = None
    ) -> typing.Any: ...
    def request_instrument_statuses(self, product_type: BitgetProductType) -> typing.Any: ...
    def request_orderbook_snapshot(
        self,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        limit: int | None = None,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def request_trades(
        self,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
    ) -> typing.Any: ...
    def request_funding_rates(
        self,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
    ) -> typing.Any: ...
    def request_bars(
        self,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        bar_type: model.BarType,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
        timestamp_on_close: bool = False,
    ) -> typing.Any: ...
    def request_account_state(
        self,
        product_type: BitgetProductType,
        account_id: model.AccountId,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def request_order_status_report(
        self,
        account_id: model.AccountId,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        venue_order_id: str | None = None,
        client_order_id: str | None = None,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def request_order_status_reports(
        self,
        account_id: model.AccountId,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        open_only: bool = False,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def request_fill_reports(
        self,
        account_id: model.AccountId,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def request_position_status_reports(
        self,
        account_id: model.AccountId,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def submit_order(
        self,
        product_type: BitgetProductType,
        trader_id: model.TraderId,
        strategy_id: model.StrategyId,
        instrument_id: model.InstrumentId,
        client_order_id: model.ClientOrderId,
        order_side: model.OrderSide,
        order_type: model.OrderType,
        quantity: model.Quantity,
        time_in_force: model.TimeInForce,
        price: model.Price | None = None,
        trigger_price: model.Price | None = None,
        trigger_type: model.TriggerType | None = None,
        post_only: bool = False,
        reduce_only: bool = False,
        quote_quantity: bool = False,
        params: dict | None = None,
        ts_event_ns: int | None = None,
        ts_init_ns: int | None = None,
    ) -> typing.Any: ...
    def cancel_order(
        self,
        product_type: BitgetProductType,
        instrument_id: model.InstrumentId,
        client_order_id: model.ClientOrderId,
        venue_order_id: model.VenueOrderId | None = None,
        params: dict | None = None,
    ) -> typing.Any: ...

@typing.final
class BitgetInstrumentProviderConfig:
    def __init__(
        self, product_type: BitgetProductType | None = None, include_inactive: bool | None = None
    ) -> None: ...

@typing.final
class BitgetRawHttpClient:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        environment: BitgetEnvironment = ...,
        base_url: str | None = None,
        timeout_secs: int = 60,
        proxy_url: str | None = None,
        account_mode: BitgetAccountMode = ...,
    ) -> None: ...
    def cancel_all_requests(self) -> None: ...

@typing.final
class BitgetWebSocketClient:
    def __init__(
        self,
        product_type: BitgetProductType = ...,
        environment: BitgetEnvironment = ...,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        url: str | None = None,
        private: bool = False,
        heartbeat_secs: int = 30,
        proxy_url: str | None = None,
        http_url: str | None = None,
        http_timeout_secs: int = 60,
        account_mode: BitgetAccountMode = ...,
    ) -> None: ...
    @staticmethod
    def new_public(
        product_type: BitgetProductType = ...,
        environment: BitgetEnvironment = ...,
        url: str | None = None,
        heartbeat_secs: int = 30,
        proxy_url: str | None = None,
        http_url: str | None = None,
        http_timeout_secs: int = 60,
        account_mode: BitgetAccountMode = ...,
    ) -> BitgetWebSocketClient: ...
    @staticmethod
    def new_private(
        product_type: BitgetProductType = ...,
        environment: BitgetEnvironment = ...,
        api_key: str | None = None,
        api_secret: str | None = None,
        api_passphrase: str | None = None,
        url: str | None = None,
        heartbeat_secs: int = 30,
        proxy_url: str | None = None,
        http_url: str | None = None,
        http_timeout_secs: int = 60,
        account_mode: BitgetAccountMode = ...,
    ) -> BitgetWebSocketClient: ...
    @property
    def url(self) -> str: ...
    def is_active(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def connect(
        self, loop_: typing.Any | None = None, callback: typing.Any | None = None
    ) -> typing.Any: ...
    def wait_until_active(self, timeout_secs: float = 5.0) -> typing.Any: ...
    def disconnect(self) -> typing.Any: ...
    def close(self) -> typing.Any: ...
    def subscription_count(self) -> typing.Any: ...
    def cache_instruments(self, instruments: typing.Sequence[typing.Any]) -> None: ...
    def cache_instrument(self, instrument: typing.Any) -> None: ...
    def send_text(self, payload: str) -> typing.Any: ...
    def next_event(self) -> typing.Any: ...
    def subscribe_ticker(self, raw_symbol: str) -> typing.Any: ...
    def subscribe_trades(self, raw_symbol: str) -> typing.Any: ...
    def subscribe_books(self, raw_symbol: str) -> typing.Any: ...
    def subscribe_book_deltas(
        self, instrument_id: model.InstrumentId, depth: int | None = None
    ) -> typing.Any: ...
    def subscribe_book_depth10(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def subscribe_candles(self, raw_symbol: str, interval: str) -> typing.Any: ...
    def subscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def subscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def subscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def subscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_book_deltas(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_book_depth10(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_trade_ticks(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def unsubscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def subscribe_account(self, coin: str | None = None) -> typing.Any: ...
    def subscribe_orders(self) -> typing.Any: ...
    def subscribe_fills(self) -> typing.Any: ...
    def subscribe_positions(self) -> typing.Any: ...
    def subscribe_strategy_orders(self) -> typing.Any: ...

@typing.final
class BitgetAccountMode(enum.Enum):
    UTA = ...
    CLASSIC = ...

    def __init__(self, value: typing.Any) -> None: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @staticmethod
    def variants() -> list[str]: ...
    @classmethod
    def from_str(cls, data: typing.Any) -> BitgetAccountMode: ...

@typing.final
class BitgetEnvironment(enum.Enum):
    MAINNET = ...
    DEMO = ...

    def __init__(self, value: typing.Any) -> None: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @staticmethod
    def variants() -> list[str]: ...
    @classmethod
    def from_str(cls, data: typing.Any) -> BitgetEnvironment: ...

@typing.final
class BitgetProductType(enum.Enum):
    SPOT = ...
    USDT_FUTURES = ...

    def __init__(self, value: typing.Any) -> None: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @staticmethod
    def variants() -> list[str]: ...
    @classmethod
    def from_str(cls, data: typing.Any) -> BitgetProductType: ...

def bitget_bar_spec_to_interval(aggregation: int, step: int) -> str: ...
def bitget_extract_raw_symbol(symbol: str) -> str: ...
def bitget_product_type_from_symbol(symbol: str) -> BitgetProductType: ...
def get_bitget_http_base_url(environment: BitgetEnvironment) -> str: ...
def get_bitget_ws_url_private(environment: BitgetEnvironment, account_mode: BitgetAccountMode = ...) -> str: ...
def get_bitget_ws_url_public(environment: BitgetEnvironment, account_mode: BitgetAccountMode = ...) -> str: ...
